# Generated by Django 5.0.4 on 2024-04-09 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='financialInvoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posting_type', models.CharField(choices=[('expense', 'expense'), ('revenue', 'revenue')], default='expense', max_length=50)),
                ('payment_description', models.CharField(max_length=250)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('due_date', models.DateField()),
                ('payee', models.CharField(blank=True, max_length=250, null=True)),
                ('document_number', models.CharField(blank=True, max_length=250, null=True)),
                ('category', models.CharField(max_length=250)),
                ('bank_account', models.CharField(max_length=100)),
                ('card', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, max_length=300, null=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('paid', 'paid'), ('canceled', 'canceled'), ('overdue', 'overdue')], default='pending', max_length=250)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
